name: 'Terraform Plan'
description: 'Terraform Plan running in loop save each data product tf_plan individually'
inputs:
  terraform_directory:
    description: ''
    required: true
  terraform_gcp_sa_key:
    description: 'JSON key for GCP service account'
    required: true    
  github_token:
    description: 'Token used for resourses related with git'
    required: true    
  github_owner:
    description: 'Project used for resourses related with git'
    required: false
    default: ""
  data_product_list:
    description: 'List with data products to plan'
    required: true 

runs:
  using: "composite"
  
  steps:
    # Generates an Terraform plan for each data product
    - name: Terraform Plan
      id: plan
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      env:
        GOOGLE_CREDENTIALS: ${{ inputs.terraform_gcp_sa_key }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_OWNER: ${{ inputs.github_owner }}
        DATA_PRODUCTS: ${{ inputs.data_product_list }}
      run: |
        echo 'plan<<EOF' >> $GITHUB_OUTPUT
        for dp in $DATA_PRODUCTS; do
          terraform plan -var='data_product=$dp' -var-file=variables.tfvars -no-color -out="$dp-tfplan" >> $GITHUB_OUTPUT
        done
        echo 'EOF' >> $GITHUB_OUTPUT