name: 'IAC FOR DATA PRODUCTS - CI'

on:
  pull_request:

permissions:
  contents: read

jobs:
  terraform_plan:
    if: github.event.review.state != 'approved'
    uses: ./.github/workflows/plan.yml
    with:
      data_product: data-product-a
