name: 'IAC FOR DATA PRODUCTS - CI'

on:
  pull_request:

permissions:
  contents: read

env:
  GOOGLE_CREDENTIALS = ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  terraform_plan:
    if: github.event.review.state != 'approved'
    uses: ./.github/workflows/plan.yml
    with:
      data_product: data-product-a
      terraform_gcp_sa_key: ${{ env.GOOGLE_CREDENTIALS }}
